import React from 'react'

const create ="Create imaginative and visually stunning images generated by DALL-E AI and share them with community"
const home = "Browse through a collection of imaginative and visually stunning images generated by DALL-E AI"

const Header = ({title}) => {
  return (
    <div>
    <h1 className='font-extrabold text-[#222328] text-[32px]'>{title}</h1>
    <p className='mt-2 text-[#666e75] text-[16px] max-w-[500px]'>
      {title === "Create" ? create: home}
    </p>
  </div>
  )
}

export default Header